## Emojis
Words that co-occur with emojis in tweets

In [36]:
import pandas as pd
import numpy as np
import re

from collections import Counter
from cytoolz import concat

pd.set_option('precision', 2)
pd.set_option('display.max_rows', 20)
pd.set_option('display.max_colwidth', 250)
%pprint

Pretty printing has been turned OFF

In [37]:
# pd.set_option('display.max_rows', 30)
# 'Pretty printing has been turned ON'

In [17]:
df.head()

,created_at,favorite_count,favorited,filter_level,id_str,in_reply_to_screen_name,in_reply_to_status_id_str,in_reply_to_user_id_str,lang,place,possibly_sensitive,retweet_count,retweeted,search_region,source_clean,text,truncated,user
0,2014-12-13 04:54:17,0,False,medium,543629961978847232,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.117116, 32.582128], [-117.117116, 32.685406], [-116.9278103, 32.685406], [-116.9278103, 32.582128]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'C...",False,0,False,San Diego region,Twitter for iPhone,This why I can't play 2k w yall 😭,False,"{'contributors_enabled': False, 'created_at': 'Tue Aug 23 23:07:00 +0000 2011', 'default_profile': True, 'default_profile_image': False, 'description': 'Cj White|Former Varsity Pearland DB | future civil engineer and buisness owner|', 'favourites..."
1,2014-12-10 23:58:22,0,False,medium,542830714937290752,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.1244522, 32.64634], [-117.1244522, 32.69328], [-117.049103, 32.69328], [-117.049103, 32.64634]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'Natio...",False,0,False,San Diego region,Twitter for Android,mood: empty,False,"{'contributors_enabled': False, 'created_at': 'Tue Dec 17 00:24:18 +0000 2013', 'default_profile': False, 'default_profile_image': False, 'description': 'phora ♡', 'favourites_count': 1918, 'follow_request_sent': None, 'followers_count': 250, 'fo..."
2,2014-12-08 05:46:15,0,False,medium,541831098951430144,Rafamere,5.42e+17,2.76e+09,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.117116, 32.582128], [-117.117116, 32.685406], [-116.9278103, 32.685406], [-116.9278103, 32.582128]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'C...",False,0,False,San Diego region,Twitter for iPhone,@Rafamere but I did ...,False,"{'contributors_enabled': False, 'created_at': 'Fri Nov 14 05:52:51 +0000 2014', 'default_profile': True, 'default_profile_image': False, 'description': 'SanDiego, California ig; seebastiann_', 'favourites_count': 373, 'follow_request_sent': None,..."
3,2014-12-09 23:35:39,0,False,medium,542462612336680960,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.282538, 32.53962], [-117.282538, 33.0804044], [-116.9274403, 33.0804044], [-116.9274403, 32.53962]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'S...",False,0,False,San Diego region,Twitter for iPhone,"i continue to experience butterflies in my stomach when the stewardess says ""welcome to san diego."" #2ndHomeLove",False,"{'contributors_enabled': False, 'created_at': 'Wed Sep 02 21:26:51 +0000 2009', 'default_profile': False, 'default_profile_image': False, 'description': 'meaning-seeking, daughter lovin', people watching, God praising, light recording, 6' bohemia..."
4,2014-12-12 06:49:19,0,False,medium,543296523359244288,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-124.482003, 32.528832], [-124.482003, 42.009519], [-114.131212, 42.009519], [-114.131212, 32.528832]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'Cal...",False,0,False,San Diego region,Twitter for Android,Nikka we made it! :))) http://t.co/WbK7XpSPsL,False,"{'contributors_enabled': False, 'created_at': 'Wed May 29 07:00:57 +0000 2013', 'default_profile': True, 'default_profile_image': False, 'description': None, 'favourites_count': 2515, 'follow_request_sent': None, 'followers_count': 183, 'followin..."

In [15]:
df = pd.read_json('tweets.json.gz', lines=True)

Look up one row of a DataFrame via its index using df.loc[]

In [18]:
df.loc[0]

created_at                                                                                                                                                                                                                                                         2014-12-13 04:54:17
favorite_count                                                                                                                                                                                                                                                                       0
favorited                                                                                                                                                                                                                                                                        False
filter_level                                                                                                                                                                                                                                                                    medium
id_str                                                                                                                                                                                                                                                              543629961978847232
in_reply_to_screen_name                                                                                                                                                                                                                                                           None
in_reply_to_status_id_str                                                                                                                                                                                                                                                          NaN
in_reply_to_user_id_str                                                                                                                                                                                                                                                            NaN
lang                                                                                                                                                                                                                                                                                en
place                        {'attributes': {}, 'bounding_box': {'coordinates': [[[-117.117116, 32.582128], [-117.117116, 32.685406], [-116.9278103, 32.685406], [-116.9278103, 32.582128]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'C...
possibly_sensitive                                                                                                                                                                                                                                                               False
retweet_count                                                                                                                                                                                                                                                                        0
retweeted                                                                                                                                                                                                                                                                        False
search_region                                                                                                                                                                                                                                                         San Diego region
source_clean                                                                                                                                                                                                                                                        Twitter for iPhone
text                                                                                                                                                                                                                                                 This why I can't play 2k w yall 😭
truncated                                                                                                                                                                                                                                                                        False
user                         {'contributors_enabled': False, 'created_at': 'Tue Aug 23 23:07:00 +0000 2011', 'default_profile': True, 'default_profile_image': False, 'description': 'Cj White|Former Varsity Pearland DB | future civil engineer and buisness owner|', 'favourites...
Name: 0, dtype: object

or One column using df[]

In [19]:
df['text']

0                                                                                                                This why I can't play 2k w yall 😭
1                                                                                                                                      mood: empty
2                                                                                                                          @Rafamere but I did ...
3                                 i continue to experience butterflies in my stomach when the stewardess says "welcome to san diego." #2ndHomeLove
4                                                                                                    Nikka we made it! :))) http://t.co/WbK7XpSPsL
5                                                                                                                      I don't fuckin care bum ass
6                                                                                                         My parents never knowledge my grades wow
7                                                                                                    Feels so good to be back in the gym again 😭😭😭
8                                            ain't gonna lie, i still think of you, care for you, love you. but i have too much pride to admit it.
9                                                                                    @TedGanas The fine is irrelevant to whether they knew or not.
10                                                                                                                 No estas gorda @cacahuetesrosas
11             @deeshif @JERRADV @Henry_The_Fifth @BlasingameBryan @MrMichaelBorne @DJHypaWhyte - happy Freakshow Wednesday http://t.co/B10CRnhiQl
12                                      All of the sudden Mayweather wants to fight Manny 😂 sit your ass down👇 OK. We'll see the real winner now 👏
13                                                                                           My roommates and another girl and I watched kill bill
14                                                                                               OH.MY.GODDDD YES!!!!!!!!!! http://t.co/g4hUocoIbo
                                                                            ...
249985    “@BestHairstyIes: GOALS x1000 http://t.co/l9HvKNSeJb” lmao I thought this was a joke, it's cubic zirconia, I don't fuck w that fake shit
249986                                             @fuckboy4l @lucifredo i followed you back. I'll just mute you next time you're being annoying 😊
249987          I have mixed feeling for this upcoming storm. I need you so I can have more time to study and I don't because you'll bring damage.
249988                                                                                         @AngelIbarrra Oscar said : "Baby Angel said that?😥"
249989                                                                                                                                      K cool
249990                                                                                                Why do gossip columnists talk like snitches?
249991                                                                                           Early Christmas present 😭😍 http://t.co/Auoks8Unxb
249992                  @MikelSevere @nfldraftscout @Koorsones Johnson, Hyde, lynch, Borland, Johnson, dial, carradine have all produced this year
249993                                                                                            https://t.co/28HDOwT6E6 It's levels to this shit
249994                                                                        “@Dance10Nico: some throwback improv :) https://t.co/w3lrIn327D” bae
249995                                                                                                              #word 👊 http://t.co/bo7yetFbhT
249996                                                                                                                             Can't fake real
249997                                                                    "@RavishingKee_: Swear to god I feel like killing somebody"pray about it
249998                                                                                                                        Bitch you guessed it
249999                                                                                                                   @allenhklee — BibleThump7
Name: text, Length: 250000, dtype: object

or Both:

In [20]:
df.loc[0, 'text']

"This why I can't play 2k w yall 😭"

<b> Boolean Indexing

In [21]:
df['source_clean'] == 'Twitter for iPhone'

0          True
1         False
2          True
3          True
4         False
5          True
6         False
7          True
8          True
9          True
10        False
11        False
12        False
13         True
14        False
          ...
249985     True
249986     True
249987     True
249988     True
249989     True
249990     True
249991     True
249992     True
249993     True
249994     True
249995     True
249996     True
249997    False
249998    False
249999     True
Name: source_clean, Length: 250000, dtype: bool

In [22]:
df[df['source_clean'] == 'Twitter for iPhone']

,created_at,favorite_count,favorited,filter_level,id_str,in_reply_to_screen_name,in_reply_to_status_id_str,in_reply_to_user_id_str,lang,place,possibly_sensitive,retweet_count,retweeted,search_region,source_clean,text,truncated,user
0,2014-12-13 04:54:17,0,False,medium,543629961978847232,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.117116, 32.582128], [-117.117116, 32.685406], [-116.9278103, 32.685406], [-116.9278103, 32.582128]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'C...",False,0,False,San Diego region,Twitter for iPhone,This why I can't play 2k w yall 😭,False,"{'contributors_enabled': False, 'created_at': 'Tue Aug 23 23:07:00 +0000 2011', 'default_profile': True, 'default_profile_image': False, 'description': 'Cj White|Former Varsity Pearland DB | future civil engineer and buisness owner|', 'favourites..."
2,2014-12-08 05:46:15,0,False,medium,541831098951430144,Rafamere,5.42e+17,2.76e+09,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.117116, 32.582128], [-117.117116, 32.685406], [-116.9278103, 32.685406], [-116.9278103, 32.582128]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'C...",False,0,False,San Diego region,Twitter for iPhone,@Rafamere but I did ...,False,"{'contributors_enabled': False, 'created_at': 'Fri Nov 14 05:52:51 +0000 2014', 'default_profile': True, 'default_profile_image': False, 'description': 'SanDiego, California ig; seebastiann_', 'favourites_count': 373, 'follow_request_sent': None,..."
3,2014-12-09 23:35:39,0,False,medium,542462612336680960,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.282538, 32.53962], [-117.282538, 33.0804044], [-116.9274403, 33.0804044], [-116.9274403, 32.53962]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'S...",False,0,False,San Diego region,Twitter for iPhone,"i continue to experience butterflies in my stomach when the stewardess says ""welcome to san diego."" #2ndHomeLove",False,"{'contributors_enabled': False, 'created_at': 'Wed Sep 02 21:26:51 +0000 2009', 'default_profile': False, 'default_profile_image': False, 'description': 'meaning-seeking, daughter lovin', people watching, God praising, light recording, 6' bohemia..."
5,2014-12-09 15:40:50,0,False,medium,542343119123914752,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.053546, 32.743581], [-117.053546, 32.7958], [-116.981714, 32.7958], [-116.981714, 32.743581]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'La Mesa...",False,0,False,San Diego region,Twitter for iPhone,I don't fuckin care bum ass,False,"{'contributors_enabled': False, 'created_at': 'Mon Feb 28 02:19:20 +0000 2011', 'default_profile': False, 'default_profile_image': False, 'description': 'careless | taz ass | charlies angel fym| If you not D1 then your d**k ain't either one hunna..."
7,2014-12-17 04:57:45,0,False,medium,545080383914520576,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-124.482003, 32.528832], [-124.482003, 42.009519], [-114.131212, 42.009519], [-114.131212, 32.528832]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'Cal...",False,0,False,San Diego region,Twitter for iPhone,Feels so good to be back in the gym again 😭😭😭,False,"{'contributors_enabled': False, 'created_at': 'Mon Sep 10 04:46:33 +0000 2012', 'default_profile': False, 'default_profile_image': False, 'description': 'Made in Algeria. Raised in Los Scandalous. Follow me on instagram: @khadidjaboo', 'favourite..."
8,2014-12-14 00:33:46,0,False,medium,543926786644398080,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.282538, 32.53962], [-117.282538, 33.0804044], [-116.9274403, 33.0804044], [-116.9274403, 32.53962]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'S...",False,0,False,San Diego region,Twitter for iPhone,"ain't gonna lie, i still think of you, care for you, love you. but i have too much pride to admit it.",False,"{'contributors_enabled': False, 'created_at': 'Thu May 15 15:15:33 +0000 2014', 'default_profile': True, 'default_profile_image': False, 'description': None, 'favourites_count': 1094, 'follow_request_sent': None, 'followers_count': 344, 'followin..."
9,2014-12-16 03:30:15,0,False,medium,544695975470968832,TedGanas,5.45e+17,2.29e+09,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.288262, 33.1312307], [-117.288262, 33.23861], [-117.191297, 33.23861], [-117.191297, 33.1312307]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'Vis...",False,0,False,San Diego region,Twitter for iPhone,@TedGanas The fine is irrelevant to whether they knew or not.,False,"{'contributors_enabled': False, 'created_at': 'Sun Apr 11 16:32:57 +0000 2010', 'default_profile': True, 'default_profile_image': False, 'description': 'LA Kings Sec 322. Denver Broncos, Dodgers, Beer, Running.', 'favourites_count': 6771, 'follow..."
13,2014-12-18 08:15:37,0,False,medium,545492565596712960,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.282538, 32.53962], [-117.282538, 33.0804044], [-116.9274403, 33.0804044], [-116.9274403, 32.53962]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'S...",False,0,False,San Diego region,Twitter for iPhone,My roommates and another girl and I watched kill bill,False,"{'contributors_enabled': False, 'created_at': 'Thu Jun 18 20:39:12 +0000 2009', 'default_profile': False, 'default_profile_image': False, 'description': 'partypooper2k14 and the most hella of them all (speak english with me/habla espanol conmigo/..."
15,2014-12-21 01:45:46,0,False,medium,546481622347177984,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.288262, 33.1312307], [-117.288262, 33.23861], [-117.191297, 33.23861], [-117.191297, 33.1312307]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'Vis...",False,0,False,San Diego region,Twitter for iPhone,I just love waking up 20 minutes before my shift !!!😅,False,"{'contributors_enabled': False, 'created_at': 'Wed Nov 14 04:08:15 +0000 2012', 'default_profile': True, 'default_profile_image': False, 'description': 'Bossed Up Need No Help', 'favourites_count': 10000, 'follow_request_sent': None, 'followers_c..."
16,2014-12-11 06:45:46,0,False,medium,542933242090115072,Leslaaaaaay,5.43e+17,6.33e+07,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.282538, 32.53962], [-117.282538, 33.0804044], [-116.9274403, 33.0804044], [-116.9274403, 32.53962]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'S...",False,0,False,San Diego region,Twitter for iPhone,@Leslaaaaaay @cali_dalliance at Chatas!!?,False,"{'contributors_enabled': False, 'created_at': 'Fri Oct 04 12:54:20 +0000 2013', 'default_profile': True, 'default_profile_image': False, 'description': None, 'favourites_count': 261, 'follow_request_sent': None, 'followers_count': 10, 'following'..."
17,2014-12-08 20:03:17,0,False,medium,542046778602692608,ConnorFranta,NaN,1.81e+08,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-124.482003, 32.528832], [-124.482003, 42.009519], [-114.131212, 42.009519], [-114.131212, 32.528832]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'Cal...",False,0,False,San Diego region,Twitter for iPhone,@ConnorFranta you rock 💃,False,"{'contributors_enabled': False, 'created_at': 'Mon Jul 30 03:54:14 +0000 2012', 'default_profile': False, 'default_profile_image': False, 'description': 'fries before guys', 'favourites_count': 2039, 'follow_request_sent': None, 'followers_count'..."
18,2014-12-12 07:29:18,0,False,medium,543306586114904064,Connor_Hale2,5.43e+17,4.08e+08,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.282538, 32.53962], [-117.282538, 33.0804044], [-116.9274403, 33.0804044], [-116.9274403, 32.53962]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'S...",False,0,False,San Diego region,Twitter for iPhone,@Connor_Hale2 I'll smack you tonight if you want,False,"{'contributors_enabled': False, 'created_at': 'Sun Mar 27 06:14:01 +0000 2011', 'default_profile': False, 'default_profile_image': False, 'description': '20 | full-time chiller ⛄️| Lakers | Steelers | Halos', 'favourites_count': 6825, 'follow_req..."
20,2014-12-11 00:37:50,0,False,medium,542840646294589440,None,NaN,NaN,es,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.2984211, 32.0982919], [-117.2984211, 32.567461], [-116.5597831, 32.567461], [-116.5597831, 32.0982919]]], 'type': 'Polygon'}, 'country': 'México', 'country_code': 'MX', 'full_name': 'Tiju...",False,0,False,San Diego region,Twitter for iPhone,Es hora de ver la TV,False,"{'contributors_enabled': False, 'created_at': 'Sun Sep 26 02:02:38 +0000 2010', 'default_profile': False, 'default_profile_image': False, 'description': 'soy xoolos me gusta @patycantu soy fan de @moeniamx y también soy united forever', 'favouri..."
21,2014-12-20 20:26:48,0,False,medium,546401351048372224,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-124.482003, 32.528832], [-124.482003, 42.009519], [-114.131212, 42.009519], [-114.131212, 32.528832]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'Cal...",False,0,False,San Diego region,Twitter for iPhone,"You made me the best CD mix ever. Like I love every single song, they're all so good ☺️ thanks babe😍 @liberalpizza",False,"{'contributors_enabled': False, 'created_at': 'Sun Sep 22 01:17:00 +0000 2013', 'default_profile': False, 'default_profile_image': False, 'description': '17, Senior // #FutureBulldog // i love boonville //', 'favourites_count': 11716, 'follow_req..."
22,2014-12-22 22:59:50,0,False,medium,547164639268986880,naroutunian,5.47e+17,2.71e+09,und,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-124.482003, 32.528832], [-124.482003, 42.009519], [-114.131212, 42.009519], [-114.131212, 32.528832]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'Cal...",False,0,False,San Diego region,Twitter for iPhone,@naroutunian http://t.co/LYsklSmIVS,False,"{'contributors_enabled': False, 'created_at': 'Thu Nov 12 08:31:35 +0000 2009', 'default_profile': False, 'default_profile_image': False, 'description': 'instagram/snapchat : thebananaannaa', 'favourites_count': 9301, 'follow_request_sent': None,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249982,2014-12-12 04:39:42,0,False,medium,543263902826364928,None,NaN,NaN,und,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.184394, 33.447541], [-117.184394, 33.554501], [-117.054639, 33.554501], [-117.054639, 33.447541]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'Tem...",False,0,False,San Diego region,Twitter for iPhone,#SecretAngel,False,"{'contributors_enabled': False, 'created_at': 'Sat Nov 13 02:44:24 +0000 2010', 'default_profile': False, 'default_profile_image': False, 'description': 'Licensed Marriage Family Therapist, Doctoral Candidate, political aficionado, sports nut, an..."
249983,2014-12-08 01:00:13,0,False,medium,541759115291553792,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.1244522, 32.64634], [-117.1244522, 32.69328], [-117.049103, 32.69328], [-117.049103, 32.64634]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'Natio...",False,0,False,San Diego region,Twitter for iPhone,When babe be laggin when yall be texting😒👋,False,"{'contributors_enabled': False, 'created_at': 'Tue May 20 20:38:57 +0000 2014', 'default_profile': True, 'default_profile_image': False, 'description': None, 'favourites_count': 52, 'follow_request_sent': None, 'followers_count': 61, 'following':..."
249985,2014-12-11 18:14:21,0,False,medium,543106528660955136,BestHairstyIes,5.43e+17,2.20e+09,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.282538, 32.53962], [-117.282538, 33.0804044], [-116.9274403, 33.0804044], [-116.9274403, 32.53962]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'S...",False,0,False,San Diego region,Twitter for iPhone,"“@BestHairstyIes: GOALS x1000 http://t.co/l9HvKNSeJb” lmao I thought this was a joke, it's cubic zirconia, I don't fuck w that fake shit",False,"{'contributors_enabled': False, 'created_at': 'Tue Jun 12 20:07:44 +0000 2012', 'default_profile': False, 'default_profile_image': False, 'description': 'god is a fat black lady', 'favourites_count': 30242, 'follow_request_sent': None, 'followers..."
249986,2014-12-16 03:51:36,0,False,medium,544701347946168320,fuckboy4l,5.45e+17,2.42e+08,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-124.482003, 32.528832], [-124.482003, 42.009519], [-114.131212, 42.009519], [-114.131212, 32.528832]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'Cal...",False,0,False,San Diego region,Twitter for iPhone,@fuckboy4l @lucifredo i followed you back. I'll just mute you next time you're being annoying 😊,False,"{'contributors_enabled': False, 'created_at': 'Sat Oct 10 23:12:24 +0000 2009', 'default_profile': False, 'default_profile_image': False, 'description': 'im Jon Messing around im Lockwood poetic', 'favourites_count': 4831, 'follow_request_sent': ..."
249987,2014-12-11 14:20:31,0,False,medium,543047681677873152,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-124.482003, 32.528832], [-124.482003, 42.009519], [-114.131212, 42.009519], [-114.131212, 32.528832]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'Cal...",False,0,False,San Diego region,Twitter for iPhone,I have mixed feeling for this upcoming storm. I need you so I can have more time to study and I don't because you'll bring damage.,False,"{'contributors_enabled': False, 'created_at': 'Sun May 06 06:07:47 +0000 2012', 'default_profile': False, 'default_profile_image': False, 'description': 'Bands ❤️ Music // Basically what's on my mind • I really dislike some people • I hate this w..."
249988,2014-12-10 21:12:33,0,False,medium,542788986880536576,AngelIbarrra,5.43e+17,7.59e+08,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.359298, 33.0606148], [-117.359298, 33.1823533], [-117.216549, 33.1823533], [-117.216549, 33.0606148]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': ...",False,0,False,San Diego region,Twitter for iPhone,"@AngelIbarrra Oscar said : ""Baby Angel said that?😥""",False,"{'contributors_enabled': False, 'created_at': 'Fri Oct 18 20:04:41 +0000 2013', 'default_profile': True, 'default_profile_image': False, 'description': None, 'favourites_count': 9698, 'follow_request_sent': None, 'followers_count': 181, 'followin..."
249989,2014-12-13 18:05:02,0,False,medium,543828960526598144,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.282538, 32.53962], [-117.282538, 33.0804044], [-116.9274403, 33.0804044], [-116.9274403, 32.53962]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'S...",False,0,False,San Diego region,Twitter for iPhone,K cool,False,"{'contributors_enabled': False, 'created_at': 'Sat Dec 31 00:29:27 +0000 2011', 'default_profile': False, 'default_profile_image': False, 'description': None, 'favourites_count': 3884, 'follow_request_sent': None, 'followers_count': 163, 'followi..."
249990,2014-12-08 04:43:27,0,False,medium,541815296843997184,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.282538, 32.53962], [-117.282538, 33.0804044], [-116.9274403, 33.0804044], [-116.9274403, 32.53962]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'S...",False,0,False,San Diego region,Twitter for iPhone,Why do gossip columnists talk like snitches?,False,"{'contributors_enabled': False, 'created_at': 'Sat Sep 19 01:14:49 +0000 2009', 'default_profile': False, 'default_profile_image': False, 'description': 'Yogi, musical savant, political pundit, cold champagne consumer.', 'favourites_count': 3863,..."
249991,2014-12-24 06:07:55,0,False,medium,547634757941477376,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.288262, 33.1312307], [-117.288262, 33.23861], [-117.191297, 33.23861], [-117.191297, 33.1312307]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'Vis...",False,0,False,San Diego region,Twitter for iPhone,Early Christmas present 😭😍 http://t.co/Auoks8Unxb,False,"{'contributors_enabled': False, 'created_at': 'Mon Jun 24 10:04:47 +0000 2013', 'default_profile': True, 'default_profile_image': False, 'description': 'happy', 'favourites_count': 24838, 'follow_request_sent': None, 'followers_count': 464, 'foll..."
249992,2014-12-15 01:10:45,0,False,medium,544298481959985152,MikelSevere,5.44e+17,3.87e+07,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.359298, 33.0606148], [-117.359298, 33.1823533], [-117.216549, 33.1823533], [-117.216549, 33.0606148]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': ...",False,0,False,San Diego region,Twitter for iPhone,"@MikelSevere @nfldraftscout @Koorsones Johnson, Hyde, lynch, Borland, Johnson, dial, carradine have all produced this year",False,"{'contributors_enabled': False, 'created_at': 'Fri Jul 29 18:12:22 +0000 2011', 'default_profile': True, 'default_profile_image': False, 'description': 'Not all martyrs see divinity. But at least you tried. -Maynard James Keenan Ju..."
249993,2014-12-24 00:18:13,0,False,medium,547546755030470656,None,NaN,NaN,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.1244522, 32.64634], [-117.1244522, 32.69328], [-117.049103, 32.69328], [-117.049103, 32.64634]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'Natio...",False,0,False,San Diego region,Twitter for iPhone,https://t.co/28HDOwT6E6 It's levels to this shit,False,"{'contributors_enabled': False, 'created_at': 'Mon Jul 30 02:50:36 +0000 2012', 'default_profile': False, 'default_profile_image': False, 'description': 'Fred Burton.San Diego,California #GKBM #goodkushbettermuseic #wemajorsd #fredburtontheep #gk..."
249994,2014-12-10 03:33:26,0,False,medium,542522452060798976,Dance10Nico,5.43e+17,1.41e+09,en,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-124.482003, 32.528832], [-124.482003, 42.009519], [-114.131212, 42.009519], [-114.131212, 32.528832]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'Cal...",False,0,False,San Diego region,Twitter for iPhone,“@Dance10Nico: some throwback improv :) https://t.co/w3lrIn327D” bae,False,"{'contributors_enabled': False, 'created_at': 'Sat Jan 01 21:02:22 +0000 2011', 'default_profile': False, 'default_profile_image': False, 'description': 'Napa || SLO', 'favourites_count': 7840, 'follow_request_sent': None, 'followers_count': 438,..."
249995,2014-12-16 04:57:15,0,False,medium,544717872933523456,None,NaN,NaN,und,"{'attributes': {}, 'bounding_box': {'coordinates': [[[-117.282538, 32.53962], [-117.282538, 33.0804044], [-116.9274403, 33.0804044], [-116.9274403, 32.53962]]], 'type': 'Polygon'}, 'country': 'United States', 'country_code': 'US', 'full_name': 'S...",False,0,False,San Diego region,Twitter for iPhone,#word 👊 http://t.co/bo7yetFbhT,False,"{'contributors_enabled': False, 'created_at': 'Sun Jun 28 23:02:20 +0000 2009', 'default_profile': False, 'default_profile_image': False, 'description': 'Love God & love others... the rest is all Baptist politics.', 'fa..."

Find: how 😂 is used on Twitter. 
How: search for occuerrences of 😂, but this has the same unicode as A or ॐ.

    So look up by name in the Unicode character DB:

In [23]:
'\N{face with tears of joy}'

'😂'

In [24]:
'\N{BIOHAZARD SIGN}'

'☣'

In [25]:
'\N{LATIN CAPITAL LETTER M}'

'M'

<b> use <i> NLTK TweetTokenizer </i></b> to normalize/tokenize texts:

In [32]:
from nltk.tokenize import TweetTokenizer
T = TweetTokenizer(preserve_case = False, reduce_len = True, strip_handles = True)

In [29]:
df.loc[12]['text']

"All of the sudden Mayweather wants to fight Manny 😂 sit your ass down👇 OK. We'll see the real winner now 👏"

In [30]:
T.tokenize(df.loc[12]['text'])

['all',
 'of',
 'the',
 'sudden',
 'mayweather',
 'wants',
 'to',
 'fight',
 'manny',
 '😂',
 'sit',
 'your',
 'ass',
 'down',
 '👇',
 'ok',
 '.',
 "we'll",
 'see',
 'the',
 'real',
 'winner',
 'now',
 '👏']

Create a new column ('tokens')
Result of applying the tokenizer to each text:

In [33]:
df['tokens'] = df['text'].apply(T.tokenize)

## Counting words

In [34]:
df.loc[0:10, 'tokens']

0                                                                                                  [this, why, i, can't, play, 2k, w, yall, 😭]
1                                                                                                                             [mood, :, empty]
2                                                                                                                           [but, i, did, ...]
3     [i, continue, to, experience, butterflies, in, my, stomach, when, the, stewardess, says, ", welcome, to, san, diego, ., ", #2ndhomelove]
4                                                                                   [nikka, we, made, it, !, :), ), ), http://t.co/WbK7XpSPsL]
5                                                                                                           [i, don't, fuckin, care, bum, ass]
6                                                                                             [my, parents, never, knowledge, my, grades, wow]
7                                                                                [feels, so, good, to, be, back, in, the, gym, again, 😭, 😭, 😭]
8       [ain't, gonna, lie, ,, i, still, think, of, you, ,, care, for, you, ,, love, you, ., but, i, have, too, much, pride, to, admit, it, .]
9                                                                             [the, fine, is, irrelevant, to, whether, they, knew, or, not, .]
10                                                                                                                          [no, estas, gorda]
Name: tokens, dtype: object

In [35]:
list(concat(df.loc[0:10, 'tokens']))

['this',
 'why',
 'i',
 "can't",
 'play',
 '2k',
 'w',
 'yall',
 '😭',
 'mood',
 ':',
 'empty',
 'but',
 'i',
 'did',
 '...',
 'i',
 'continue',
 'to',
 'experience',
 'butterflies',
 'in',
 'my',
 'stomach',
 'when',
 'the',
 'stewardess',
 'says',
 '"',
 'welcome',
 'to',
 'san',
 'diego',
 '.',
 '"',
 '#2ndhomelove',
 'nikka',
 'we',
 'made',
 'it',
 '!',
 ':)',
 ')',
 ')',
 'http://t.co/WbK7XpSPsL',
 'i',
 "don't",
 'fuckin',
 'care',
 'bum',
 'ass',
 'my',
 'parents',
 'never',
 'knowledge',
 'my',
 'grades',
 'wow',
 'feels',
 'so',
 'good',
 'to',
 'be',
 'back',
 'in',
 'the',
 'gym',
 'again',
 '😭',
 '😭',
 '😭',
 "ain't",
 'gonna',
 'lie',
 ',',
 'i',
 'still',
 'think',
 'of',
 'you',
 ',',
 'care',
 'for',
 'you',
 ',',
 'love',
 'you',
 '.',
 'but',
 'i',
 'have',
 'too',
 'much',
 'pride',
 'to',
 'admit',
 'it',
 '.',
 'the',
 'fine',
 'is',
 'irrelevant',
 'to',
 'whether',
 'they',
 'knew',
 'or',
 'not',
 '.',
 'no',
 'estas',
 'gorda']

In [38]:
f = Counter(concat(df.loc[0:10, 'tokens']))
f

Counter({'i': 6, 'to': 5, '😭': 4, '.': 4, 'my': 3, 'the': 3, ',': 3, 'you': 3, 'but': 2, 'in': 2, '"': 2, 'it': 2, ')': 2, 'care': 2, 'this': 1, 'why': 1, "can't": 1, 'play': 1, '2k': 1, 'w': 1, 'yall': 1, 'mood': 1, ':': 1, 'empty': 1, 'did': 1, '...': 1, 'continue': 1, 'experience': 1, 'butterflies': 1, 'stomach': 1, 'when': 1, 'stewardess': 1, 'says': 1, 'welcome': 1, 'san': 1, 'diego': 1, '#2ndhomelove': 1, 'nikka': 1, 'we': 1, 'made': 1, '!': 1, ':)': 1, 'http://t.co/WbK7XpSPsL': 1, "don't": 1, 'fuckin': 1, 'bum': 1, 'ass': 1, 'parents': 1, 'never': 1, 'knowledge': 1, 'grades': 1, 'wow': 1, 'feels': 1, 'so': 1, 'good': 1, 'be': 1, 'back': 1, 'gym': 1, 'again': 1, "ain't": 1, 'gonna': 1, 'lie': 1, 'still': 1, 'think': 1, 'of': 1, 'for': 1, 'love': 1, 'have': 1, 'too': 1, 'much': 1, 'pride': 1, 'admit': 1, 'fine': 1, 'is': 1, 'irrelevant': 1, 'whether': 1, 'they': 1, 'knew': 1, 'or': 1, 'not': 1, 'no': 1, 'estas': 1, 'gorda': 1})

In [39]:
f['to']

5

In [40]:
subset = df['text'].str.contains('😂')
freq = pd.DataFrame({'all':Counter(concat(df['tokens'])),
                    '😂':Counter(concat(df[subset]['tokens']))})

In [41]:
freq.head(10)

                      all       😂
!                   49426  1733.0
"                   20694  2407.0
#                     446    10.0
###lovethisguy          1     NaN
##all1dcrewcontest      1     NaN
##christmas             1     NaN
##gopackgo              1     NaN
##lemthurdy             1     NaN
##sandiego              1     NaN
#06010                  1     NaN

In [42]:
freq.loc['!']

all    49426.0
😂       1733.0
Name: !, dtype: float64

In [43]:
freq.sort_values('all', ascending = False)

                          all       😂
i                       70000  4106.0
.                       62987  1625.0
the                     50822  2390.0
!                       49426  1733.0
to                      47613  2053.0
a                       39700  1896.0
you                     38684  2170.0
my                      34044  2036.0
,                       28734   973.0
and                     28573  1404.0
...                       ...     ...
http://t.co/FR708T0NGd      1     NaN
http://t.co/FR6D04Y9u7      1     NaN
http://t.co/FR1H47EDpS      1     NaN
http://t.co/FQh0eE5RXP      1     NaN
http://t.co/FQV4ABXGdq      1     NaN
http://t.co/FQK6Ur6qdl      1     NaN
http://t.co/FQEtjSgloU      1     NaN
http://t.co/FQ9YOvq1sp      1     NaN
http://t.co/FPzMdFaHzt      1     NaN
󾬏                           1     NaN

[144215 rows x 2 columns]

In [44]:
freq['pmi'] = np.log2( ( freq['😂'] * np.sum(freq['all']) ) /
                       ( freq['all'] * np.sum(freq['😂']) ) )

In [46]:
freq.sort_values('pmi', ascending = False)

                             all    😂   pmi
https://t.co/5xH7h9J87v        1  1.0  4.06
https://t.co/LlCKiGsROI        1  1.0  4.06
hisses                         1  1.0  4.06
https://t.co/IsjTlYvXQi        1  1.0  4.06
https://t.co/J2qLa6fXHR        1  1.0  4.06
https://t.co/JMivxUdjwV        1  1.0  4.06
https://t.co/JPvHGFhKkL        1  1.0  4.06
https://t.co/KdqPJIxbcc        1  1.0  4.06
https://t.co/KjLKkt3osq        1  1.0  4.06
https://t.co/L3CyioB8Vw”😂😂😂    1  1.0  4.06
...                          ...  ...   ...
🚩                              6  NaN   NaN
🚪                              1  NaN   NaN
🚯                              4  NaN   NaN
🚳                              1  NaN   NaN
🚷                              2  NaN   NaN
🚹                              1  NaN   NaN
🚺                              3  NaN   NaN
🛀                             12  NaN   NaN
󾓮                              1  NaN   NaN
󾬏                              1  NaN   NaN

[144215 rows x 3 columns]

In [47]:
freq[freq['all'] > 250].sort_values('pmi', ascending = False).head(10)

            all        😂   pmi
😂         21370  21370.0  4.06
cried       254    153.0  3.33
🐶           346    153.0  2.88
💀          1697    539.0  2.40
yall        616    184.0  2.31
dying       282     80.0  2.24
laughing    277     61.0  1.87
lmfao       414     87.0  1.81
funny       911    187.0  1.77
✋           331     63.0  1.66

Pretty printing has been turned OFF

<b> Load the data</b>

FileNotFoundError: [Errno 2] No such file or directory: 'tweets.json.gz'

FileNotFoundError: [Errno 2] No such file or directory: 'tweets.json.gz'